url:
date_format: ordinal
title: 绝情可乐瓶
subtitle: 三里清风三里路 步步风里步步你
keywords: nice
timezone: Asia/Shanghai
encoding: UTF-16

author: 绝情可乐瓶
location: 重庆

navs:
  - href: /
    label: 首页
  - href: /categories/
    label: 分类

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:title/
plugins:
  - jekyll-github-metadata
  - rouge
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

repository: alltuoha/alltuoha.github.io
